print(5==5)      # True
print(5!=3)      # True
print(10>7)      # True
print(4<2)       # False
print(6>=6)      # True
print(3<=1)      # False
print("apple"=="apple")  # True
print("cat"!="dog")      # True
print(7>10)      # False
print(2<5)       # True
print(8>=8)      # True
print(9<=4)      # False
print(15==15)    # True
print(20!=20)    # False
print(3>1)       # True
print(1<0)       # False
print(12>=10)    # True
print(5<=5)      # True